"""Lesson 07 — Document loading & parsing.

The same PDF, parsed several ways, to show what *loading* (recover the text) and
*parsing* (recover the structure) actually do — and where a naive text dump quietly
loses information that retrieval later depends on.

Run from the repo root:

    uv run python -m lessons.07-document-loading-and-parsing.demo

The sample PDF (``data/acme-cloud-plans.pdf``) is a fictional two-column "plan
comparison" sheet with a pricing table. It is generated by ``make_sample_pdf.py``
and committed under ``data/``; it is invented content, not a real product. No LLM
and no network are involved — only PDF parsing libraries — so the output is fully
reproducible.
"""

from __future__ import annotations

from pathlib import Path

import pdfplumber
from pypdf import PdfReader

PDF = Path(__file__).parent / "data" / "acme-cloud-plans.pdf"


def rule(title: str) -> None:
    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)


def _trim_blank_lines(text: str) -> str:
    """Drop leading/trailing whitespace-only lines (layout=True pads to page height)."""
    lines = text.split("\n")
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(line.rstrip() for line in lines)


def table_to_markdown(rows: list[list[str]]) -> str:
    """Serialize a recovered table grid to Markdown so a chunk keeps its structure."""
    header, *body = rows
    out = ["| " + " | ".join(header) + " |", "| " + " | ".join(["---"] * len(header)) + " |"]
    for row in body:
        out.append("| " + " | ".join(c or "" for c in row) + " |")
    return "\n".join(out)


def main() -> None:
    if not PDF.exists():
        raise SystemExit(
            f"Missing {PDF}. Generate it first:\n"
            "  uv run python -m lessons.07-document-loading-and-parsing.make_sample_pdf"
        )

    # ------------------------------------------------------------------
    # 1. NAIVE LOAD — pypdf reads text in the PDF's content-stream order.
    # ------------------------------------------------------------------
    reader = PdfReader(str(PDF))
    rule("1. NAIVE EXTRACTION  (pypdf — content-stream order)")
    print("Page 1 (two-column prose):\n")
    print(reader.pages[0].extract_text())
    print("\nPage 2 (the pricing TABLE), extracted as plain text:\n")
    print(reader.pages[1].extract_text())

    with pdfplumber.open(str(PDF)) as pdf:
        page1, page2 = pdf.pages[0], pdf.pages[1]

        # --------------------------------------------------------------
        # 2. GEOMETRY ORDER — pdfplumber's default sorts by position
        #    (top-to-bottom), which reads straight ACROSS both columns.
        # --------------------------------------------------------------
        rule("2. GEOMETRY-ORDER EXTRACTION  (pdfplumber default — top-to-bottom)")
        print("Page 1, same file — note the two columns are now interleaved:\n")
        print(page1.extract_text())

        # --------------------------------------------------------------
        # 3. LAYOUT-PRESERVING — keep the visual geometry so the two
        #    columns are visible as columns (positions, not reading order).
        # --------------------------------------------------------------
        rule("3. LAYOUT-PRESERVING EXTRACTION  (pdfplumber layout=True)")
        print("Page 1 — whitespace mimics the page; you can SEE two columns:\n")
        print(_trim_blank_lines(page1.extract_text(layout=True)))

        # --------------------------------------------------------------
        # 4. STRUCTURE-AWARE TABLE EXTRACTION — recover the 2-D grid.
        # --------------------------------------------------------------
        rule("4. STRUCTURE-AWARE TABLE EXTRACTION  (pdfplumber extract_table)")
        table = page2.extract_table()
        print("Page 2 table recovered as rows (each row is a Python list):\n")
        for row in table:
            print(" ", row)
        print("\nSerialized to Markdown — structure survives into the chunk:\n")
        print(table_to_markdown(table))


if __name__ == "__main__":
    main()
